import fs from 'fs';
import path from 'path';
import glob from 'glob';
import chalk from 'chalk';
import { executeAiRequest, buildAiPrompt } from './api';

export class BugHunter {
    /**
     * Reads a sample of project files and performs deep AI static analysis to find logic edge cases.
     */
    public async huntForBugs(provider: string, maxFiles = 10) {
        console.log(chalk.red.bold(`\n🕵️‍♂️ Autonomous Bug Hunter Initiated`));
        console.log(chalk.gray(`Scanning project for silent logic flaws and memory leaks...`));

        const files = glob.sync('src/**/*.{ts,js,py,go,rs,cpp,java}', { ignore: ['node_modules/**', 'dist/**'] });
        
        // Randomly shuffle to sample different files if project is large
        const sampleFiles = files.sort(() => 0.5 - Math.random()).slice(0, maxFiles);
        let bountyReport = `# 🕵️‍♂️ Autonomous Bug Bounty Report\n\nGenerated by G-Coder v5.0\n\n`;
        let bugsFound = 0;

        for (const file of sampleFiles) {
            console.log(chalk.cyan(`Analyzing ${file}...`));
            const absolutePath = path.resolve(process.cwd(), file);
            const content = fs.readFileSync(absolutePath, 'utf-8');

            const prompt = `Act as an elite Security Auditor and Bug Hunter.
Analyze the following code for silent edge cases, memory leaks, race conditions, or unhandled exceptions.
If the code is perfectly safe, output EXACTLY "CLEAN". 
If you find a bug, describe the bug briefly and provide the corrected code snippet.

File: ${file}
Content:
${content.substring(0, 3000)}`;

            try {
                const analysis = await executeAiRequest(buildAiPrompt('ask', prompt, 'architect'), provider);
                if (!analysis.includes('CLEAN')) {
                    bugsFound++;
                    console.log(chalk.yellow(`⚠ Potential flaw detected in ${file}!`));
                    bountyReport += `## File: ${file}\n${analysis}\n\n---\n\n`;
                } else {
                    console.log(chalk.green(`✔ ${file} is clean.`));
                }
            } catch (e: any) {
                console.log(chalk.gray(`Skipped ${file} due to API limits.`));
            }
        }

        if (bugsFound === 0) {
            console.log(chalk.green.bold(`\n✅ Codebase is highly resilient. No bugs found in the sample.`));
        } else {
            const reportPath = path.resolve(process.cwd(), 'BUG_BOUNTY_REPORT.md');
            fs.writeFileSync(reportPath, bountyReport, 'utf-8');
            console.log(chalk.green.bold(`\n✅ Hunt complete! ${bugsFound} issues documented in BUG_BOUNTY_REPORT.md`));
        }
    }
}
